services:
  api-dev:
    build:
      target: dev
      dockerfile: Dockerfile
      context: ./api
    volumes:
      - .:/api
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - PORT=${API_PORT}
      - APP_ORIGIN=${APP_ORIGIN}
      - HOST=${HOST}

  api:
    build:
      target: prod
      dockerfile: Dockerfile
      context: ./api
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - PORT=${API_PORT}
      - APP_ORIGIN=${APP_ORIGIN}
      - HOST=${HOST}
